language: node_js
node_js:
- "8"
cache:
  directories:
<<<<<<< HEAD
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE c4sg;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('mysql') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: c4sg-dev
    staging: c4sg-staging
    prod: c4sg-prod
=======
  - node_modules
script:
- npm run lint
- npm run test_single_run
>>>>>>> upstream/master
